#!/bin/bash -

set -x
gpu=7
runs=3
for dataset in pubmed flickr ppi arxiv yelp reddit; do
	# SGC
	time python3 -u node.pyc MLP $dataset --precompute 2 --runs $runs --gpu $gpu 2>&1
    # ECN (SC)
	time python3 -u node.pyc ECN $dataset --skip-connection --precompute 1 --runs $runs --gpu $gpu 2>&1
    # GraphSAGE (P)
	time python3 -u node.pyc GraphSAGE $dataset --precompute 1 --runs $runs --gpu $gpu 2>&1
	# GraphSAGE
	time python3 -u node.pyc GraphSAGE $dataset --precompute 0 --runs $runs --gpu $gpu 2>&1
	# FastGCN
	time python3 -u node.pyc FastGCN $dataset --precompute 1 --runs $runs --gpu $gpu 2>&1
	# GraphSAINT
	time python3 -u node.pyc GraphSAINT $dataset --precompute 0 --runs $runs --gpu $gpu 2>&1
    # GCN (P)
	time python3 -u node.pyc GCN $dataset --precompute 1 --runs $runs --gpu $gpu 2>&1
done | tee -a logs/$0.log
