#!/bin/bash -

set -x
gpu=6
gpu2=7
runs=3
for hidden in 128 256 512 1024 2048; do
	for dropout in 0.0 0.1 0.2 0.3 0.4 0.5; do
		for weight_decay in 0 0.1 0.01 0.001 0.0001; do
			time python3 -u node.pyc ECN \
				pubmed \
				--no-importance-sampling \
				--skip-connection \
				--embedding 0.0 \
				--precompute 2 \
				--hidden $hidden \
				--weight-decay $weight_decay \
				--dropout $dropout \
				--runs $runs \
				--gpu $gpu 2>&1
			time python3 -u node.pyc ECN \
				flickr \
				--embedding 0.1 \
				--attention 32 \
				--precompute 2 \
				--hidden $hidden \
				--weight-decay $weight_decay \
				--dropout $dropout \
				--runs $runs \
				--gpu $gpu 2>&1
			time python3 -u node.pyc ECN \
				ppi \
				--skip-connection \
				--embedding 0.1 \
				--precompute 3 \
				--hidden $hidden \
				--weight-decay $weight_decay \
				--dropout $dropout \
				--runs $runs \
				--gpu $gpu 2>&1
			time python3 -u node.pyc ECN \
				arxiv \
				--embedding 0.1 \
				--precompute 2 \
				--hidden $hidden \
				--weight-decay $weight_decay \
				--dropout $dropout \
				--runs $runs \
				--gpu $gpu 2>&1
			time python3 -u node.pyc ECN \
				yelp \
				--skip-connection \
				--embedding 0.01 \
				--precompute 0 \
				--hidden $hidden \
				--weight-decay $weight_decay \
				--dropout $dropout \
				--runs $runs \
				--gpu $gpu 2>&1
			time python3 -u node-reddit.pyc ECN \
				reddit \
				--skip-connection \
				--precompute 3 \
				--hidden $hidden \
				--weight-decay $weight_decay \
				--dropout $dropout \
				--runs $runs \
                --gpu2 $gpu2 \
				--gpu $gpu 2>&1
            for dataset in pubmed flickr ppi arxiv yelp reddit; do
                time python3 -u node.pyc MLP $dataset \
                    --precompute 0 \
                    --hidden $hidden \
                    --weight-decay $weight_decay \
                    --dropout $dropout \
                    --runs $runs \
                    --gpu $gpu 2>&1
                time python3 -u node.pyc MLP $dataset \
                    --precompute -1 \
                    --hidden $hidden \
                    --weight-decay $weight_decay \
                    --dropout $dropout \
                    --runs $runs \
                    --gpu $gpu 2>&1
            done
            for dataset in pubmed flickr ppi arxiv; do
                time python3 -u node.pyc GCN $dataset \
                    --precompute 1 \
                    --hidden $hidden \
                    --weight-decay $weight_decay \
                    --dropout $dropout \
                    --runs $runs \
                    --gpu $gpu 2>&1
            done
		done
	done
done | tee -a logs/$0.log
